name: timed
description: Calculates the time interval between two dates in seconds, minutes, days, weeks, months, or years.
version: 0.0.1+2
homepage: https://github.com/srnunio/timed
repository: https://github.com/srnunio/timed

environment:
  sdk: '>=2.18.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
